name: The Foto Company
favicon: null
layout_spectrum: 0.6298764233943075
typography_spectrum: 0.13006916432641447
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3125244826078415
  lightness: 0.9593982505612075
  saturation: 0.41099056345410645
  rhythmicContrast: 0.510611233767122
purpose: []
